export const FORM_ERROR = 'FORM_ERROR';
export const CLEAR_FORM_ERROR = 'CLEAR_FORM_ERROR';

export const SIGN_UP = 'SIGN_UP';

export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const UPDATE_USER = 'UPDATE_USER';

export const CHANGE_PROFILE_PIC = 'CHANGE_PROFILE_PIC';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const UPLOAD_POST = 'UPLOAD_POST';
export const OPEN_UPLOAD_POST = 'OPEN_UPLOAD_POST';
export const CLOSE_UPLOAD_POST = 'CLOSE_UPLOAD_POST';
export const GET_PROFILE_POSTS = 'GET_PROFILE_POSTS';
export const GET_PROFILE_POSTS_SUCCESS = 'GET_PROFILE_POSTS_SUCCESS';

export const GET_SUGGESTIONS = 'GET_SUGGESTIONS';
export const GET_SUGGESTIONS_SUCCESS = 'GET_SUGGESTIONS_SUCCESS';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const FOLLOW = 'FOLLOW';
export const FOLLOW_SUCESS = 'FOLLOW_SUCESS';
export const FOLLOW_SUCESS_SUGGESTIONS = 'FOLLOW_SUCESS_SUGGESTIONS';
export const UNFOLLOW = 'UNFOLLOW';

export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
